# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'combobox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cb_football_team = QtWidgets.QComboBox(self.centralwidget)
        self.cb_football_team.setGeometry(QtCore.QRect(330, 90, 321, 31))
        self.cb_football_team.setObjectName("cb_football_team")
        self.get_item = QtWidgets.QPushButton(self.centralwidget)
        self.get_item.setGeometry(QtCore.QRect(330, 150, 321, 41))
        self.get_item.setObjectName("get_item")
        self.load_items = QtWidgets.QPushButton(self.centralwidget)
        self.load_items.setGeometry(QtCore.QRect(330, 210, 321, 41))
        self.load_items.setObjectName("load_items")
        self.clear_items = QtWidgets.QPushButton(self.centralwidget)
        self.clear_items.setGeometry(QtCore.QRect(330, 270, 321, 41))
        self.clear_items.setObjectName("clear_items")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(330, 330, 661, 341))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.label_result.setFont(font)
        self.label_result.setObjectName("label_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.get_item.setText(_translate("MainWindow", "get item"))
        self.load_items.setText(_translate("MainWindow", "load items"))
        self.clear_items.setText(_translate("MainWindow", "clear items"))
        self.label_result.setText(_translate("MainWindow", "TextLabel"))
